In [1]:
import numpy as np

arr = np.array([1,2,3,4,5])
result = arr **2
result

array([ 1,  4,  9, 16, 25])

# broadcasting

In [4]:
arr = np.array([1,2,3,4,5])

result = arr + 10
result

# here 10 is broadcast across all element of an array

array([11, 12, 13, 14, 15])

# Broad casting with Arrays of different Shapes


In [5]:
# 2D array in 2D array

a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

result = a1 + a2
result

array([5, 7, 9])

In [7]:
# 2D array in 1D array

a1 = np.array([[1,2,3], [9,8,7]])
a2 = np.array([4,5,6])

a1 + a2



array([[ 5,  7,  9],
       [13, 13, 13]])