# Creating arrays from scratch:

In [4]:
# for a matrix of all zero     use = zeros
import numpy as np
a = np.zeros((3, 3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
# for a matrix all ones         use = ones

import numpy as np
b = np.ones((2, 4))
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
# for any matrrix order but filled with any one elements

import numpy as np

c = np.full((2,2) , 8)
c

array([[8, 8],
       [8, 8]])

In [11]:
# for any identity matrix of order n              use .eye
 
import numpy as np

d = np.eye(5)
d

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
# here 1-1000 is range and 10 is the addition at every step

e = np.arange(1, 1000 , 10)
e

array([  1,  11,  21,  31,  41,  51,  61,  71,  81,  91, 101, 111, 121,
       131, 141, 151, 161, 171, 181, 191, 201, 211, 221, 231, 241, 251,
       261, 271, 281, 291, 301, 311, 321, 331, 341, 351, 361, 371, 381,
       391, 401, 411, 421, 431, 441, 451, 461, 471, 481, 491, 501, 511,
       521, 531, 541, 551, 561, 571, 581, 591, 601, 611, 621, 631, 641,
       651, 661, 671, 681, 691, 701, 711, 721, 731, 741, 751, 761, 771,
       781, 791, 801, 811, 821, 831, 841, 851, 861, 871, 881, 891, 901,
       911, 921, 931, 941, 951, 961, 971, 981, 991])

In [15]:
# for equally spaced array

h = np.linspace(1, 100, 10)
h

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [19]:
arr = np.array([[1,2,3],[4,5,6],[8,57,43],[12,21,543]])
arr.shape


(4, 3)

In [20]:
arr.size


12

In [21]:

arr.ndim


2

In [22]:


arr.dtype

dtype('int64')

# Changing Data Types


In [23]:
# this is a explicit method


arr = np.array([[1,2,3],[4,5,6],[8,57,43],[12,21,543]], dtype='float32')

In [24]:
arr

array([[  1.,   2.,   3.],
       [  4.,   5.,   6.],
       [  8.,  57.,  43.],
       [ 12.,  21., 543.]], dtype=float32)

In [25]:
# convert float into int

arr_int = arr.astype(np.int32)
arr_int

array([[  1,   2,   3],
       [  4,   5,   6],
       [  8,  57,  43],
       [ 12,  21, 543]], dtype=int32)

# Reshaping and Flattening arrays

In [28]:
arr = np.array([[1,2,3],[4,5,6],[8,57,43],[12,21,543]])

arr

array([[  1,   2,   3],
       [  4,   5,   6],
       [  8,  57,  43],
       [ 12,  21, 543]])

In [29]:
arr.shape

(4, 3)

In [30]:
reshaped = arr.reshape((3, 4))

In [31]:
reshaped

array([[  1,   2,   3,   4],
       [  5,   6,   8,  57],
       [ 43,  12,  21, 543]])

In [32]:
flattened = arr.flatten()

In [33]:
flattened

array([  1,   2,   3,   4,   5,   6,   8,  57,  43,  12,  21, 543])