In [1]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6],[8,57,43],[12,21,543]])

In [2]:
arr

array([[  1,   2,   3],
       [  4,   5,   6],
       [  8,  57,  43],
       [ 12,  21, 543]])

In [5]:
flat = arr.flatten()
flat

array([  1,   2,   3,   4,   5,   6,   8,  57,  43,  12,  21, 543])

In [6]:
flat[0]

np.int64(1)

In [7]:
flat[3: 6]

array([4, 5, 6])

In [8]:
sir = np.array([  1,   2,   3,   4,   5,   6,   8,  57,  43,  12,  21, 543])

In [10]:
sir[[1 , 3, 5]]

array([2, 4, 6])

In [12]:
sir[sir>33]

array([ 57,  43, 543])

# lets practice some question

- create a 3 X 3 array filled with random number and print its shape

In [5]:
import numpy as np

arr = np.random.randint(1, 31, (3, 3))
arr

array([[ 2,  3, 29],
       [12, 23,  7],
       [28,  2, 11]], dtype=int32)

In [6]:
print(arr.shape)

(3, 3)


- convert an array of floats [1.1, 2.2 , 3.3]  into integers

In [9]:
a = np.array([1.1, 2.2, 3.3, ])
b = a.astype('int')
b

array([1, 2, 3])

- use fancy indexing to extract even number from [1,2,3,4,5,6]

In [10]:
i = np.array([1,2,3,4,5,6])
idx = [1 ,3 , 5]
print(i[idx])

[2 4 6]


- Reshape a 1D array of size 9 into a 3X3 matrix

In [11]:
r = np.array([1,2,3,4,5,6,7,8,9])
reshaped = r.reshape((3,3))
reshaped

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])