In [1]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [2]:
arr[0]

array([1, 2, 3])

In [3]:
arr[1]

array([4, 5, 6])

In [4]:
arr[2]

array([7, 8, 9])

In [5]:
arr[1,2]

np.int64(6)

In [6]:
print(np.sum(arr, axis=0))


[12 15 18]


In [7]:
print(np.sum(arr, axis=1))

[ 6 15 24]


In [8]:
print(arr[1,2])

6


In [9]:
print(arr[0:2 , 1:3])

[[2 3]
 [5 6]]


In [22]:
arr3D = np.array([
    [[1,2,3], 
     [4,5,6]],
    
    [[7,8,9],
     [10,11,12]]
])
arr3D.shape


(2, 2, 3)

In [23]:
print(arr3D[0,1,2])

6


In [24]:
print(arr3D[:, 0, :])

[[1 2 3]
 [7 8 9]]


In [28]:
arr3D[:, 0, :] = 1
arr3D

array([[[ 1,  1,  1],
        [ 4,  5,  6]],

       [[ 1,  1,  1],
        [10, 11, 12]]])